/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdagesRouteImport } from './routes/adages'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiLinkPreviewRouteImport } from './routes/api/link-preview'
import { Route as ApiSpotifyRouteImport } from './routes/api/spotify'
import { Route as ApiTestGeoRouteImport } from './routes/api/test-geo'
import { Route as ApiVisitorLocationRouteImport } from './routes/api/visitor-location'
import { Route as ApiAdagesImagesSplatRouteImport } from './routes/api/adages-images.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdagesRoute = AdagesRouteImport.update({
  id: '/adages',
  path: '/adages',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkPreviewRoute = ApiLinkPreviewRouteImport.update({
  id: '/api/link-preview',
  path: '/api/link-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyRoute = ApiSpotifyRouteImport.update({
  id: '/api/spotify',
  path: '/api/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestGeoRoute = ApiTestGeoRouteImport.update({
  id: '/api/test-geo',
  path: '/api/test-geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitorLocationRoute = ApiVisitorLocationRouteImport.update({
  id: '/api/visitor-location',
  path: '/api/visitor-location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdagesImagesSplatRoute = ApiAdagesImagesSplatRouteImport.update({
  id: '/api/adages-images/$',
  path: '/api/adages-images/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adages': typeof AdagesRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/spotify': typeof ApiSpotifyRoute
  '/api/test-geo': typeof ApiTestGeoRoute
  '/api/visitor-location': typeof ApiVisitorLocationRoute
  '/api/adages-images/$': typeof ApiAdagesImagesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adages': typeof AdagesRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/spotify': typeof ApiSpotifyRoute
  '/api/test-geo': typeof ApiTestGeoRoute
  '/api/visitor-location': typeof ApiVisitorLocationRoute
  '/api/adages-images/$': typeof ApiAdagesImagesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adages': typeof AdagesRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/spotify': typeof ApiSpotifyRoute
  '/api/test-geo': typeof ApiTestGeoRoute
  '/api/visitor-location': typeof ApiVisitorLocationRoute
  '/api/adages-images/$': typeof ApiAdagesImagesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adages'
    | '/history'
    | '/notes'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/link-preview'
    | '/api/spotify'
    | '/api/test-geo'
    | '/api/visitor-location'
    | '/api/adages-images/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adages'
    | '/history'
    | '/notes'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/link-preview'
    | '/api/spotify'
    | '/api/test-geo'
    | '/api/visitor-location'
    | '/api/adages-images/$'
  id:
    | '__root__'
    | '/'
    | '/adages'
    | '/history'
    | '/notes'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/link-preview'
    | '/api/spotify'
    | '/api/test-geo'
    | '/api/visitor-location'
    | '/api/adages-images/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdagesRoute: typeof AdagesRoute
  HistoryRoute: typeof HistoryRoute
  NotesRoute: typeof NotesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLinkPreviewRoute: typeof ApiLinkPreviewRoute
  ApiSpotifyRoute: typeof ApiSpotifyRoute
  ApiTestGeoRoute: typeof ApiTestGeoRoute
  ApiVisitorLocationRoute: typeof ApiVisitorLocationRoute
  ApiAdagesImagesSplatRoute: typeof ApiAdagesImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adages': {
      id: '/adages'
      path: '/adages'
      fullPath: '/adages'
      preLoaderRoute: typeof AdagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-preview': {
      id: '/api/link-preview'
      path: '/api/link-preview'
      fullPath: '/api/link-preview'
      preLoaderRoute: typeof ApiLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify': {
      id: '/api/spotify'
      path: '/api/spotify'
      fullPath: '/api/spotify'
      preLoaderRoute: typeof ApiSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-geo': {
      id: '/api/test-geo'
      path: '/api/test-geo'
      fullPath: '/api/test-geo'
      preLoaderRoute: typeof ApiTestGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visitor-location': {
      id: '/api/visitor-location'
      path: '/api/visitor-location'
      fullPath: '/api/visitor-location'
      preLoaderRoute: typeof ApiVisitorLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adages-images/$': {
      id: '/api/adages-images/$'
      path: '/api/adages-images/$'
      fullPath: '/api/adages-images/$'
      preLoaderRoute: typeof ApiAdagesImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdagesRoute: AdagesRoute,
  HistoryRoute: HistoryRoute,
  NotesRoute: NotesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLinkPreviewRoute: ApiLinkPreviewRoute,
  ApiSpotifyRoute: ApiSpotifyRoute,
  ApiTestGeoRoute: ApiTestGeoRoute,
  ApiVisitorLocationRoute: ApiVisitorLocationRoute,
  ApiAdagesImagesSplatRoute: ApiAdagesImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
